package io.github.angrylid.mall.mbg.dao;

import io.github.angrylid.mall.mbg.entity.Message;
import java.util.List;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    int deleteByPrimaryKey(Integer sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    Message selectByPrimaryKey(Integer sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    List<Message> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    int updateByPrimaryKey(Message record);
}