package io.github.angrylid.mall.mbg.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uname
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usex
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    private String usex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nation
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.date_entry
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    private Date dateEntry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.date_seperation
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    private Date dateSeperation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.department
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.position
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_admin
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    private Byte isAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.passwd
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    private String passwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uname
     *
     * @return the value of user.uname
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uname
     *
     * @param uname the value for user.uname
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usex
     *
     * @return the value of user.usex
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public String getUsex() {
        return usex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usex
     *
     * @param usex the value for user.usex
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public void setUsex(String usex) {
        this.usex = usex == null ? null : usex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nation
     *
     * @return the value of user.nation
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nation
     *
     * @param nation the value for user.nation
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.date_entry
     *
     * @return the value of user.date_entry
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public Date getDateEntry() {
        return dateEntry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.date_entry
     *
     * @param dateEntry the value for user.date_entry
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public void setDateEntry(Date dateEntry) {
        this.dateEntry = dateEntry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.date_seperation
     *
     * @return the value of user.date_seperation
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public Date getDateSeperation() {
        return dateSeperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.date_seperation
     *
     * @param dateSeperation the value for user.date_seperation
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public void setDateSeperation(Date dateSeperation) {
        this.dateSeperation = dateSeperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.department
     *
     * @return the value of user.department
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.department
     *
     * @param department the value for user.department
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.position
     *
     * @return the value of user.position
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.position
     *
     * @param position the value for user.position
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_admin
     *
     * @return the value of user.is_admin
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public Byte getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_admin
     *
     * @param isAdmin the value for user.is_admin
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public void setIsAdmin(Byte isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.passwd
     *
     * @return the value of user.passwd
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.passwd
     *
     * @param passwd the value for user.passwd
     *
     * @mbg.generated Sun Nov 21 19:57:49 CST 2021
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }
}